# Generated by Django 4.1.7 on 2023-03-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guichet', '0002_etudiant_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_d_inscription',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_de_naissance',
            field=models.DateField(null=True),
        ),
    ]
